"""empty message

Revision ID: 32a4231da64f
Revises: 5b963bfdfc31
Create Date: 2023-01-30 10:43:43.934846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a4231da64f'
down_revision = '5b963bfdfc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'rating')
    op.drop_column('novels', 'overall_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('overall_rating', sa.INTEGER(), nullable=True))
    op.add_column('comments', sa.Column('rating', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
