"""empty message

Revision ID: 5b963bfdfc31
Revises: 024039a3777b
Create Date: 2023-01-23 15:53:02.012300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b963bfdfc31'
down_revision = '024039a3777b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('overall_rating', sa.Integer(), nullable=True))
    op.drop_column('novels', 'overall_ating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('overall_ating', sa.INTEGER(), nullable=True))
    op.drop_column('novels', 'overall_rating')
    # ### end Alembic commands ###
