"""empty message

Revision ID: 9fdd210ad88d
Revises: 84b832fe4064
Create Date: 2023-01-13 15:38:59.141407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdd210ad88d'
down_revision = '84b832fe4064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'rating')
    # ### end Alembic commands ###
